export FPS=30
export RESW=360
export RESH=360

export INPUT_DIR=output/dnerf/lego_extended/video/
export OUTPUT_DIR=~/cource/lang-segment-anything/videos/lego_extended/
mkdir -p $OUTPUT_DIR

export ITER=5
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER=20
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER=60
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER=200
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER="200_+30"
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER="200_0"
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER=1000
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER="1000_+30"
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER="1000_0"
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER=5000
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER="5000_+30"
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER="5000_0"
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER=15000
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER="15000_+30"
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER="15000_0"
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER=45000
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER="45000_+30"
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4
export ITER="45000_0"
ffmpeg -y -i $INPUT_DIR/ours_$ITER/renders/%05d.png -framerate $FPS -c:v libx264 -pix_fmt yuv420p -vf "scale=$RESW:$RESH" $OUTPUT_DIR/$ITER.mp4